ALTER TABLE public.host_state
    ADD COLUMN IF NOT EXISTS latency_last_ms DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS latency_observed_at DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS latency_sample_count INTEGER NOT NULL DEFAULT 0;
